### ISSUE TITLE
ubuntu-debootstrap is deprecated

### ISSUE THREAD

**Issue by hookenz** [dreamcat4/docker-images#16]
I'm using your pipework image again and I notice that it's based on ubuntu-debootstrap which has been deprecated.  You really should switch to the official ubuntu image.

i.e. change FROM ubuntu-debootstrap:15.04 to FROM ubuntu:15.04

**Comment by dreamcat4** [comment]
OK.
Thanks @hookenz for letting me know this. I really appreciate that you took the time to mention that. Indeed I was not aware. I will be leaving this issue open until the matter is fully resolved.

My current plan was to just try and hang in there a little bit longer with those current 14.04 or 15.10 debootstrap images. Just until the new 16.04 LTS will come out this April. Since it would better to jump everything directly on to the new 16.04 in 1 go. Less annoying.

You can be sure I do wish to move to the best supported and official `ubuntu` image that is currently available. My reasons for using debootstrap to begin with were merely about image size and nothing else.

What I'm not so certain about is the best time I should do that. Since the old image is already deprecated now that puts a bit more pressure on.

We could potentially upgrade before the LTS is officially out. Either was it requires a bunch of re-testing and should not be avoided. As there is a heavy usage of these 2 images:
- Pipework
- Tvheadend

**Comment by dreamcat4** [comment]
Ah here we go:

15.10:

https://github.com/docker-library/docs/blob/master/ubuntu/tag-details.md#ubuntu1510

= 134.4 mb (+50.5 mb?)

16.04:

https://github.com/docker-library/docs/blob/master/ubuntu/tag-details.md#ubuntu1604

= 117.7 mb (+47.5 mb?)

wheras the official `ubuntu-14.04` used to be "187.9 MB" (with perhaps + 65.7 mb layer extra).

The old debootstrap image was so small. I will miss this:

``` sh
ubuntu-debootstrap    14.04   1b166211e055   5 months ago   87.07 MB
```

So definately my images will have to be getting bigger. But not as large if going directly over 16.04 because it is indeed a bit smaller than the 15.10 equivalent. And will save time as it avoids re-testing everything twice over.

Perhaps we should choose to freeze it to this weeks tag `ubuntu:xenial-20160125` until 16.04's april 22 release date.

Indeed we can see by comparing these last 2 weeks here:

https://github.com/docker-library/docs/blob/ead27c3f7e83eda01bdce103953e80b615e842bb/ubuntu/tag-details.md#ubuntuxenial-201601191

https://github.com/docker-library/docs/blob/d5f801087706a91a91f9ad204bb05435fa3b2784/ubuntu/tag-details.md#ubuntuxenial-20160125

That they did indeed make a full new tarball. = download everything again. That is why I am inclined to at first stick on the tag `ubuntu:xenial-20160125`. Up until official release. With the downside / trade-off being no new security updates until april.

That is my current plan ATM. Please leave comment or say something if any concerns / objection.

**Comment by hookenz** [comment]
No problem, just wanted to make you aware of it as I'd never seen ubuntu-debootstrap before and went to the page and noted that it was deprecated.  I'd always used the official ubuntu image myself.

**Comment by dreamcat4** [comment]
Rebuilding right now these images with ubuntu 16.04 official image. Pipework and Tvheadend. If there is no obvious breakages then will push up to git.

**Comment by dreamcat4** [comment]
Well it seems they both work. The build image size has increased by only 25.3 megabytes for pipework... so that is good news. Tvheadend image not so much (+87.7 mb). But can't be helped really.

To answer your question about debootstrap - it was just a smaller / more stripped down image size. More like a debian image. Clearly its no longer needed when the official images are a bit smaller these days.

Changes will be pushed to github during this evening. So it should rebuild with the autobuilds system either this evening or else tomorrow evening. Just depending whether or not the dockerhub choses to flake out this time.
