### ISSUE TITLE
how to support project based network using variable in compose ?

### ISSUE THREAD

**Issue by larrycai** [dreamcat4/docker-images#20]
I have setup like this  (under `docker 1.7.1`/`docker-compose 1.5.2`)

<pre>
 environment:
    - pipework_cmd_create_br_lscx=br_lscx -i eth1 @CONTAINER_NAME@ 169.254.0.3/24
    - pipework_cmd_create_br_rscx=br_rscx -i eth0 @CONTAINER_NAME@ 169.254.1.3/24
</pre>

And I want to run multi project in compose (`-p`) to enable multi instance based on same compose file. But now the bridge name is fixed `br_lscx`/`br_rscx`, which makes it conflict.

`@CONTAINER_NAME@` looks interesting.

Can I use below or other ways to achieve it?

<pre>
 environment:
    - pipework_cmd_create_br_lscx=br_@PROJECT_NAME@_lscx -i eth1 @CONTAINER_NAME@ 169.254.0.3/24
    - pipework_cmd_create_br_rscx=br_@PROJECT_NAME@_rscx -i eth0 @CONTAINER_NAME@ 169.254.1.3/24
</pre>

**Comment by dreamcat4** [comment]
> "... to enable multi instance based on same compose file."

Uhm sorry I didnt fully understand... I have never tried to use those more advanced feature myself. But it sounds like you are saying 'multi-instance'? e.g. container_1, container_2 etc? Then perhaps you can use the `@INSTANCE@` macro expansion anywhere you wish within the pipework_cmd line.

https://github.com/dreamcat4/docker-images/blob/master/pipework/2.%20Usage.md#macro-expansions

**Comment by larrycai** [comment]
`@INSTANCE` is interest, but it is used with `--scale` option.

My case is multi project, which is enabled by `docker-compose --project-name <name>`. I think it can be used to run several suite in one docker host. 

<pre>
docker-compose -p suite1 
docker-compose -p suite2
</pre>

Will be nice to have `PROJECT_NAME` macro ?  Where is related code to enable those macro ?

**Comment by dreamcat4** [comment]
So long as the `PROJECT_NAME` is get-able from the output of `docker inspect` command. Which I'm not sure myself is possible as dont use docker compose / neither is this pipework container specifically aware of compose tool.

But if yes, then sure if you would like to add the code for us, then I will be happy to accept it.

Otherwise we are adding non-universal things to the container... then you can fork instead.

Its at 2 Code points:

https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L347

and 

https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L132-L135

BTW I am using docker v1.10 now, which includes new docker networking features... so I myself have no need for this pipework tool anymore. If you would like to take over the maintainership / learn more about the project code please dive in. Would be happy to help.

**Comment by larrycai** [comment]
nice to see the code, it is elegant.

With the help of sto http://stackoverflow.com/questions/36439800/get-label-value-from-docker-inspect/ , it is possible to get `PROJECT_NAME` like below.

<pre>
projectname="$(docker inspect   --format "{{ index .Config.Labels \"com.docker.compose.project\"}}" ${c12id}"
</pre>

Let me see whether I can contribute the PR.

BTW: mostly I will switch to docker network and latest version as well.

**Comment by dreamcat4** [comment]
OK. I am happy to accept PR for master branch. Could we name the macro expansion `@COMPOSE_PROJECT_NAME@` instead? Would appreciate that.

**Comment by larrycai** [comment]
Please check PR #21

**Comment by dreamcat4** [comment]
OK larry. I merged your PR, updated my README.md files a bit. And am releasing new incremental update `v1.15` for include this new macro expansion. Many thanks.

The images are rebuilding now. Will be available soon from hub.docker.com

**Comment by larrycai** [comment]
great, happy to have name and code there.

On Wed, Apr 6, 2016 at 7:24 PM, Dreamcat4 notifications@github.com wrote:

> OK larry. I merged your PR, updated my README.md files a bit. And am
> releasing new incremental update v1.15 for include this new macro
> expansion. Many thanks.
> 
> The images are rebuilding now. Will be available soon from hub.docker.com
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dreamcat4/docker-images/issues/20#issuecomment-206320345

## 

True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)
