### ISSUE TITLE
Docker Pipework API version mismatch

### ISSUE THREAD

**Issue by tinglis1** [dreamcat4/docker-images#29]
The new docker build seems to have done something to the docker API. I get the following message. 

> Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)

I am doing some further investigation to see what is causing this. 

Additionally at the moment I am unable the get inside the container using my usual exec bash method. Trying to work out if that's something to do with my install.

**Comment by dreamcat4** [comment]
OK so version mismatch is going to be due to the docker version built inside the container being different than the docker host (engine) its running inside of. That already used to be a problem before this latest changeset. It happens whenever rebuilding the image... will just use the last released (current) docker version. And of course different users run different versions of docker host server. So its not possible for me to please everybody who uses my image. Due to docker's API changes / incompatibilities and breakages. Which may be significant or less so between docker versions.

Maybe the error can be forced to be ignored by setting an environment var. Sorry I can't quite remember but theres another closed issue here where it was previously discussed about:

https://github.com/dreamcat4/docker-images/issues/19

and

https://github.com/dreamcat4/docker-images/issues/17

For example another way to work around the issue might be to `bind:mount` the `docker` binary executable as an overlay (just like the docker socket). However in newer versions of docker I think they might have split it into some few lib .so files too. In which case those would need to be mounted too.

Not sure why you can't bash in as never encountered that myself... `docker exec -it $container_name bash` usually works for me.

**Comment by tinglis1** [comment]
I think I have found a fix for the mean time. From docker 1.10 there is an environmental variable that forces the API version.

`DOCKER_API_VERSION`

So in my instance I added the command `-e DOCKER_API_VERSION=1.22`
This seems to have resolved my issues.

So in summary.
For docker <1.10 use pipework docker container 1.1.5 or earlier.
For docker >=1.10 use 1.1.6 with environmental variable to set the API version
