### ISSUE TITLE
Initialise tv EPG grabber

### ISSUE THREAD

**Issue by bobdvb** [dreamcat4/docker-images#30]
Now, this is my first time using Docker, so I am probably doing something wrong but here is goes (be kind). I've run up the docker and tvheadend is doing fine, took me a second attempt because I needed to add the --net=host parameter for my sat>ip.  But I am getting these errors on the EPG grabber:

> 2016-09-14 08:05:23.753 [   INFO] /usr/bin/tv_grab_uk_tvguide: grab /usr/bin/tv_grab_uk_tvguide
> 2016-09-14 08:05:23.754 [ NOTICE] START: HTS Tvheadend version 4.0.9 started, running as PID:179 UID:9981 GID:9981, CWD:/ CNF:/config
> 2016-09-14 08:05:23.756 [   INFO] spawn: Executing "/usr/bin/tv_grab_uk_tvguide"
> 2016-09-14 08:05:24.626 [  ERROR] spawn: You need to configure the grabber by running it with --configure 
> 2016-09-14 08:05:24.638 [  ERROR] /usr/bin/tv_grab_uk_tvguide: no output detected
> 2016-09-14 08:05:24.638 [WARNING] /usr/bin/tv_grab_uk_tvguide: grab returned no data

From root I ran

> docker exec <ID> /usr/bin/tv_grab_uk_tvguide --configure
> and it asked me where to put the cache files, offering to put them in /root/.xmltv/cache, I accepted this default and it just sat there. I exited with ^C, and ran just /usr/bin/tv_grab_uk_tvguide, it errored with the warning about --configure, so I ran it again and entered /config/.xmltv/cache hoping that might help, again it just sat there after I ran the command and did nothing.

In practicality I think it is strange when programmes like tvh emit errors (or at least pass them) and don't actually handle them given that the returned error message tells you how to resolve the problem. This may not be a Docker issue but I don't know how to resolve it, please help.

**Comment by dreamcat4** [comment]
Hi there,
A couple of things,

1) Instead of net=host, you can create a macvlan docker network now (you will need a new version of docker like v1.11 or higher). The advantage of using dockers macvlan driver is you can then give your container its own individual ip address. The dis-advantage is that you cannot see the container on the same computer (the docker host machine itself). But it will appear on your LAN to all other local devices as its own real ethernet device. (not behind any extra NAT etc). And I can confirm it also works fine for multicast / uPNP which is whats required by SAT>IP protocol.

Switching to using a macvlan network in docker is not related to your issue here. And involved other (docker specific) setup tasks so you may wish to come back to that idea at a later time. I just thought I should mention that it works absolutely fine for connecting tvheadend server to local SAT>IP device.

2) It seems your EPG Grabber configuration in the config / EPG tab, you have enabled some XMLTV 'uk' grabber. Which would seem to make a lot of sense. However the tvheadend software is not specifically uk-focussed. Its developed for a worldwide user base... and unfortunately those free XMLTV grabbers (for UK users) have been mostly shut down by 'Atlas' who bought the stuff off BBC a couple of years ago and changed the terms of service.

If you just ensure that 'OTA EPG' is enabled in the tvheadend web config / EPG tab. Then tvheadend will use the broadcast Over-the-air EPG from FreeSAT / Astra instead. And that is completely free. It will give up to 1 week of EPG data.

Otherwise you have to pay a yearly fee (mabe $25 PA?) for for sd_json grabber. Which is as discussed on the xmltv mailinglist a fwe months ago when they shut down the free atlas service.

Another OTA EPG setting can be found in the 'adapters' section of the tvheadend web config. If you open up the configuration settings for each of the SAT>IP 'adapters' 1-4, you can see there is also a setting to choose whether each individual tuner(s) can be allowed or denied to scan for EPG data while it is in idle state (while not being used for streaming an actual channel).
