### ISSUE TITLE
what is the docker run command for PXE

### ISSUE THREAD

**Issue by timiil** [dreamcat4/docker-images#33]
hi, could anyone just give us the docker run command for the dreamcat4/PXE sample?

**Comment by Apfelwurm** [comment]
I run it with 

> docker run --restart=always -d -v "/var/pxe:/pxe" -e pxe_nic="ens18" --net host dreamcat4/pxe

Explanation:
--restart=always so it will restarts alway again
-d deattaches the containers output from your shell
-v maps the PXE folder to your file system (in this example to /var/pxe on the host)
-e sets environment Variables ( in this case the variable pxe_nic which has to be set to your !Hosts! nics name on which you want to serve the TFTP Server [get it with ip addr])
--net host maps the container directly to your hosts network stack instead of using the docker routed default 

hope it helps somebody in the future.

**Comment by wahlstedtw** [comment]
I'm having an issue with this command. It's giving me an error and the container(s) crash: `dnsmasq: process is missing required capability NET_ADMIN`

Any suggestions? 

Full clip below. 
```
$ docker run  -v "/var/pxe:/pxe" -e pxe_nic="eth1" --net host dreamcat4/pxe /bin/sh

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
Device "eth1" does not exist.
[services.d] done.

dnsmasq: process is missing required capability NET_ADMIN
[cmd] /bin/sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by wahlstedtw** [comment]
Posting an update. Adding `--cap-add=NET_ADMIN` grants the proper permissions needed to start. 

Reading through this gives some info into the issue with this risky flag. 
https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2019q1/012840.html

if anyone has a more secure option that would be helpful.

**Comment by morganmf** [comment]
Did you sort it out?
