### ISSUE TITLE
/entrypoint.sh: line 190: set: direct-phys: invalid option name

### ISSUE THREAD

**Issue by sotiris-bos** [dreamcat4/docker-images#46]
The documentation makes the assumption that we should be able to use all pipework options with this docker image.

Is the `--direct-phys` option not implemented on this?

**Comment by dreamcat4** [comment]
Yeah the script here `entrypoint.sh` is supposed to just pass all args unaltered to pipework script, the version of his `master` branch at time of the last build of this container.

Then you probably want to set `debug=true` on the envs of the pipework container, run it again and check the output in `docker logs ...`

Then in the log it should show more what is happening, and you can find the corresponding lines in either the `entrypoint.sh` or inside the pipework script itself. It just depends where the issue occurs and if called with valid args / interface is visible and exists, etc.

Never used that option before myself. Don't know about it. Actually I stopped using all this pipework several years ago since the official docker networking is much better now then it used to be... It seems the stuff you are trying to achieve here is all really complicated. Above my pay grade.

**Comment by sotiris-bos** [comment]
What I am trying to do is very simple, I just want to assign an actual physical interface (or an SR-IOV VF) to a container, rather than set up a bridge or macvlan interface.

There is no docker-only way to do this and it could be very helpful for people that want to dedicate interfaces to docker containers instead of messing with switching and routing at the kernel.

Your script is not just passing through args unaltered to pipework. It is setting up interface names beforehand and you have completely bypassed the `--direct-phys` option that exists at lines: 10-11, 341-342.

If I had any scripting skills I would do it myself and create a pull request but I only have a vague idea of how to read your entrypoint.sh

**Comment by dreamcat4** [comment]
Logs?

**Comment by dreamcat4** [comment]
Another question i have is well... why is this not a better solution these days? You don't seem to mention that either.

https://github.com/Mellanox/docker-sriov-plugin

**Comment by dreamcat4** [comment]
OK let me try to be a bit clearer about taking logs. Assuming that you are still here and cannot use any reasonable and more modern docker native driver for this `sr-iov` stuff. Such as the one I found provided by Mellanox corp above here ^^.

Anyhow. For this matter. Heres some better instruction(s):

* Find the way you are invoking / running the container for `dreamcat4/pipework` docker image.
* Add the following environment variable:  `docker run -e "debug=true"` (or equivalent for your method of running the pipework container).
* This should switch on debugging in the pipework contaner and log that all to the container's `stdout`
* Use the command `docker logs <pipework_container_name>` to dump the full logs of everything that is happening.
* Post the full logs, from the point that the container is started up.

It is also helpful to know which `run_mode`s you are using because there are different places in the script `entrypoint.sh` where `pipework` command is executed from, depending on which `run_mode`(s) you have selected.

* This script `entrypoint.sh` does not remove flags in the `docker run -e pipework_cmd=` environment variable, unless it is one of the few `@@MACRO@@`s such as container name etc. So the flag you are talking about is not recognized as one of those, it should be getting passed in. Assuming that the `pipework_cmd=` has been set correctly.

* The pipework script and/or docker automatically chooses interface names such as `eth0`, `eth1`, etc. in numerical order. If you do not specify them youself. Again this script `entrypoint.sh` does not get involved in that aspect. However if you did not specify a `-i` flag explicitly, then here it does assume that the pipework script will automatically choose the interface name to be:  `eth1`. But that assumption is only for supporting an optional feature ("create host routes"). Which has to be enabled wit a specific extra flags etc.

https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L197

So again, I don't understand why you claim such things about this. Without seeing any actual real world logs to support / show that this is happening here.

If you need further help with taking logs then please post more details about the ways you are creating and running these containers. Otherwise I simply cannot help you any futher. Thank you.

**Comment by sotiris-bos** [comment]
First of all, thanks for taking the time to go through this with me, I really do appreciate your work!

It seems to me that the set command at line 190 tries to handle the `--direct-phys` arg as its own and fails or something. I did try the mellanox sr-iov plugin but I did not find a way to make it work with dhcp, which is a big part of what I am trying to achieve here.

Here is the command I run for the pipework container:

```
# docker run --privileged --pid=host --net=host   -v /var/run/docker.sock:/docker.sock   -e run_mode=batch,daemon   -e host_routes=true   -e route_add_delay=1  -e debug=true dreamcat4/pipework
```

Here are the logs:
https://pastebin.com/EGGEpPXR

Edit: The `--direct-phys` option is not only for SR-IOV VFs but for any extra physical interfaces that exist on the docker host. I don't think you can utilize those (in an automated way) with the SR-IOV plugin.

**Comment by dreamcat4** [comment]
Hello again. Thank you for the log. It would seem that there are a couple of different problems. One of the problems you have found already. However there is another problem. So:

Can you please also provide for the client container now, (the docker compose or in whatever system you are using), the client container yaml definition or equivalent, including fully the way that you are specifying the `pipework_cmd=` on the client container. Including surrounding line(s) above and below.

It may be important to include fully the surrounding lines without editing... to make sure we can see / check for any possible quoting issue. As there does in fact appear to be a quoting issue of some kind. Or another similar type of issue going on here.

In the meantime whilst I am waiting for that I can already go and update the `dreamcat4/pipework` for the other fix... but that is only for the host_routes feature. Not this other problem.

So we cannot fully resolve the matter until we have looked further at your client container orchestration definition. As this quoting issue should not really be happening... and I cannot find the reason for the problem yet. Thank you.

**Comment by sotiris-bos** [comment]
Oh sorry, I meant to include the docker-compose file but I completely forgot in the process..

I have been using docker-compose, here is the file:

```
myapp:
  image: praqma/network-multitool
  environment:
      - pipework_cmd="--direct-phys eno1v0 @CONTAINER_NAME@ dhclient"
  net: none
```

I had also tried without the quotes in the `pipework_cmd` line, I can repeat that test for you. In general, am fully available today to do any testing you might need.

I ran `docker-compose -f docker-compose.yml.backup2 up -d` to bring the container up.

**Comment by dreamcat4** [comment]
I have now pushed the partial fix to `dreamcat4/pipework:latest` as per 

https://github.com/dreamcat4/docker-images/commit/733036a1136421f5ce52ec293191d4f8276f6740

So you can test that by appending `:latest` to your existing docker run commandline:

```sh
# docker run --privileged --pid=host --net=host   -v /var/run/docker.sock:/docker.sock   -e run_mode=batch,daemon   -e host_routes=true   -e route_add_delay=1  -e debug=true dreamcat4/pipework
```

The other issue which requires further clarification is first seen at line 283 or your pastebin / logfile. Where it says:

```sh
++ _pipework_vars='export "pipework_cmd="--direct-phys eno1v0 @CONTAINER_NAME@ dhclient""'
```

Well that is extra set of double quotes after the `pipework_cmd=` that is why I need to see your orchestration definition because when I run the `docker inspect ...` line locally in my cmdline on my existing containers it doesn't seem to include those.

For example:

```sh
$ docker inspect --format '{{range $index, $val := .Config.Env }}{{printf "%s\"\n" $val}}{{end}}' strix.smb
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
_clean=rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
_apt_clean=eval apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
s6_overlay_version=1.22.1.0"
S6_LOGGING=1"
```

There is no double quote after the `=` sign. That is what is showing up different in your pastebin logfile.

**Comment by sotiris-bos** [comment]
Yes!! It works perfectly after running the new image and removing the quotes from the `pipework_cmd` line!

I got the quotes idea from your documentation, under the `Config/cmd` section. Just to be clear, should we avoid using doublequotes at the `pipework_cmd` ?

Also, please update the dockerhub image when done.

**Comment by dreamcat4** [comment]
Ok thank you for mentioning this. Then I'm going to remove those quotes from the docs. To avoid the potential source of confusion for users.

I am also glad that the changes works, and it's not created some new bugs / error. So yes - I shall be happy to rebuild the other versions (`1.16` and `stable`) too. So long as you are not experiencing any further issue caused by that new added code today.

**Comment by sotiris-bos** [comment]
I will start setting up some containers and do some testing but I am not seeing any problems right off the bat.

One other thing, when trying to add a macvlan interface with dhclient instead of static IP it also fails. I didn't look much into it so it could be me that is doing something wrong or it could be that macvlan does not work with dhclient. Is that the case?

**Comment by dreamcat4** [comment]
Sorry I'm not sure because I always use static ip myself. You might want to check / see over on the main official pipework repository. Search old issues or raise a new one.

Closing this issue now.

**Comment by sotiris-bos** [comment]
Yeah that seems like a pipework issue, also fails with running pipework outside of the container.

Again, I can't thank you enough for your help!

**Comment by dreamcat4** [comment]
Oh i just forgot to mention 1 little thing earlier: If the mellanox sr-iov docker networking driver isn't supporting DHCP then it's probably also worth raising an issue over there. And asking them what's the matter, if it can ever be fixed etc. Since I did not see any such open issue ATM. Or maybe they have some other challenges IDK. It's just worth improving the official docker networking drivers too. Since this pipework stuff always was a hack from the very beginning. And has a lower performance for the startup times etc. Have a good day.

**Comment by kvaps** [comment]
I think I had similar problem with SR-IOV long time ago. I can append that mellanox's SR-IOVs are working pretty same like macvlan on linux, so it is just catching all the traffic with specific mac-address and the rest are going to physical one.

The bridges on SR-IOV interfaceы will not work too by the same reason:
https://superuser.com/questions/1205346/macvtap-interface-created-on-top-of-macvlan-interface-of-a-docker-container-cann/1243630#1243630

Just FYI
