### ISSUE TITLE
Files on bintray

### ISSUE THREAD

**Issue by mat-ti** [dreamcat4/docker-images#51]
Hi there,
i was looking into your Dockerfile, I'll find your serving files from the [bintray](https://bintray.com) Services. Does this [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) affect your PXE Server?

**Comment by dreamcat4** [comment]
Yes - for sure it does. I actually don't have any good migration plan for these services. So if you happen to have any other reasonable suggestions please let me know. Many thanks.

**Comment by mat-ti** [comment]
I'm planning to dockerize our PXE Environment https://codeberg.org/angestoepselt/LinuxPXE and wanted to take your version as a base. I will have a look

**Comment by dreamcat4** [comment]
unfortunately i don't seem to have enough time to do this myself! since writing and testing those previous upload scripts for bintray took several days of development time. so a similar amount of new work to rewrite that is hard for me to get a block of time for right now

however in theory, if we could upload out binary build files as release assets to github or gitlab... then that would be more stable and reliable service provider.

in particular gitlab makes sense, because if the gitlab.com website has a service issue, then gitlab can also be self-hosted too. from your own server.

so that aspect makes gitlab more preferable to github. unfortunately the thing that i really don't like about gitlab is the slowness. it's really laggy and slow compared to github. although maybe hosting on a private instance would speed things up a lot. i suppose there is page loading analytics tools built into the browser these days to actually measure that. they must be using python or something i guess. [edit] it seems that Gitlab is mostly written in Ruby.

the site you are using (codeberg.org) also looks interesting. although it does seem to be closed source. so no self hosting option. The thing is that moving git repos from place to place is easy. but having to use an entirely different JSON rest api (and then test that it works for all the different releases / uploads) is more painful process. for moving A to B

gogs looks interesting though it is missing many important features. Behind the other ones has a lot of catching up to do. Simple git repos + issue tracker... i don't see a way to upload binary assets yet. Unless it can support git-lfs. IDK

Let me know if you have any other suggestions. But you are more than welcome to fork / clone this project. And make your own solution instead. & Thanks for taking an interest

**Comment by mat-ti** [comment]
this can be closed
