### ISSUE TITLE
dhclient does not send hostname of container

### ISSUE THREAD

**Issue by joke** [dreamcat4/docker-images#6]
Hello,

the dhclient provided in the container does not send the hostname of the container used for dhcp setup. The hostname of the docker host system is send during the dhcp request instead.

The file `/etc/dhcp/dhclient.conf` specifies: `send host-name = gethostname();`.
This means the hostname is resolved to the hostname of the docker host system if the pipework container uses `net: host`.

Regards
Joke

**Comment by dreamcat4** [comment]
Thanks @joke - I appreciate this feedback. 

What I don't understand is how is the situation different for running the pipework script on the host machine? Surely running pipework normally on host would do same thing as this, ^^ as you described above?

BTW:

We also have some recent changes / other issue to look into regarding the DHCP client. So hopefully, if any problem with hostname - we can also work on it soon.

The way I use pipework (for myself), the local router has a built-in static DHCP server + local DNS - sorry I'm not too familiar with the problem exhibited by the issue. Presumably it either mean a) the container's internal hostname is set incorrect. or b) on LAN, the DNS resolves to wrong hostname if docker host's IP DNS entry is not already set.

For a) I am under some expectation that the `--hostname=` flag of `docker run` command is honored (if was set). Currently I don't set the `--hostname=` on my container, and instead it shows inside the first 12 digits of the `container_id`. Like this:

``` sh
$ docker exec -it tvh hostname
5920ffbc0b24
```

If I am wrong please say ^^. Or otherwise please show a terminal output from your local system, which indicates the problem?

**Comment by dreamcat4** [comment]
@joke - We also have these other recent issues related to pipework DHCP client:
- https://github.com/jpetazzo/pipework/commit/19bc09473b108f9ca129eca8b2ff02e7a437cf79
- https://github.com/jpetazzo/pipework/issues/150
- https://github.com/jpetazzo/pipework/issues/152

(Just in case you are interested).

**Comment by joke** [comment]
I just tested your container with the latest version of pipework. The problem seems to be solved there. pipework is executing the dhcp client commands differently now.

Regarding the problem the hostname submission to the dhcp server depends on the dhclient client version installed in your container. pipework would have the same problem if it would have been run on the docker host. But running the same pipework version on the docker host pipework might pick up a different dhcp client (udhcpc).

**Comment by joke** [comment]
I'm really sorry. With the new container version it's working.

Thank you very much.

**Comment by dreamcat4** [comment]
@joke indeed yes! 

For the other bug we may decide to change the DHCP client soon anyway. Perhaps to jerome's `udhcpc` container. Currently this `v1.0.9` image invokes the `dhclient`, the version of `ubuntu-14.04.2-trusty`. It could be better.

We shall see.

**Comment by joke** [comment]
Looking forward to it.

Thanks

**Comment by dreamcat4** [comment]
@joke 

The `dreamcat4/pipework` docker image is updated today. New version `1.1.0`. It is recommended for all to upgrade.

Reason:

The dhcp client is now changed from `dhclient` --> Jerome's new busybox `udhcpc` client. Better stability / performance. We have now also eliminate the 22 seconds of wait_sleep artificial delay. No longer needed. The new `udhcpc` client seems to be significantly more robust and performant. Now when pipework tried to aquire new dhcp leases it should not crash so frequently like it previous `dhclient` used to.

All credit to @jpetazoni. Kind Regards.
